acme_topic:
    channel: acme/channel/{id}
    handler:
        callback: 'acme.topic' #related to the getName() of your topic
chat_topic:
    channel: chat/{type}/{id}
    handler:
        callback: 'chat.topic' #related to the getName() of your topic